FROM eclipse-temurin:17-jre-focal

WORKDIR /usr/server-profile

EXPOSE 25565/udp
EXPOSE 25565/tcp

ENTRYPOINT java -Xms1G -Xmx1G -XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:+UnlockExperimentalVMOptions -XX:+ParallelRefProcEnabled -XX:+AlwaysPreTouch -XX:MaxInlineLevel=15 -jar server.jar





